# Generated by Django 2.1 on 2019-04-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190408_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifyrecord',
            name='username',
            field=models.CharField(default='', error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
