# Generated by Django 2.1 on 2019-04-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_emailverifyrecord_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, verbose_name='用户名'),
        ),
    ]
