# Generated by Django 2.1 on 2019-04-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190409_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifyrecord',
            name='has_expired',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='emailverifyrecord',
            name='has_used',
            field=models.BooleanField(default=0),
        ),
    ]
