# Generated by Django 2.1 on 2019-04-10 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190410_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverifyrecord',
            name='has_used',
        ),
    ]
