# Generated by Django 2.1 on 2019-05-19 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_emailverifyrecord_has_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='用户名')),
                ('upload_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='上传时间')),
                ('title', models.CharField(max_length=100, verbose_name='文件名')),
            ],
            options={
                'verbose_name': '上传文件信息',
                'verbose_name_plural': '上传文件信息',
            },
        ),
    ]
