# Generated by Django 2.1 on 2019-06-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_uploadfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='用户名')),
                ('check_time', models.CharField(max_length=100, verbose_name='查重时间')),
            ],
            options={
                'verbose_name': '查重信息',
                'verbose_name_plural': '查重信息',
            },
        ),
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_id', models.IntegerField(verbose_name='查重编号')),
                ('file1', models.CharField(max_length=200, verbose_name='文件1名')),
                ('file2', models.CharField(max_length=200, verbose_name='文件2名')),
                ('sim', models.FloatField(verbose_name='相似度')),
            ],
            options={
                'verbose_name': '查重结果',
                'verbose_name_plural': '查重结果',
            },
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='title',
            field=models.CharField(max_length=200, verbose_name='文件名'),
        ),
    ]
