# Generated by Django 2.1 on 2019-06-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190606_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkresult',
            name='sim',
        ),
        migrations.AddField(
            model_name='checkresult',
            name='sim1',
            field=models.FloatField(default=0, verbose_name='第一级相似度'),
        ),
        migrations.AddField(
            model_name='checkresult',
            name='sim2',
            field=models.FloatField(default=0, verbose_name='第二级相似度'),
        ),
        migrations.AddField(
            model_name='checkresult',
            name='sim3',
            field=models.FloatField(default=0, verbose_name='第三级相似度'),
        ),
    ]
