# Generated by Django 2.1 on 2019-07-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190610_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkresult',
            name='filename1',
            field=models.CharField(default='', max_length=200, verbose_name='文件1简单名字'),
        ),
        migrations.AddField(
            model_name='checkresult',
            name='filename2',
            field=models.CharField(default='', max_length=200, verbose_name='文件2简单名字'),
        ),
    ]
