# Generated by Django 2.1 on 2019-07-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190703_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInfoFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_id', models.IntegerField(verbose_name='查重编号')),
                ('filename', models.CharField(max_length=200, verbose_name='查重文件名')),
            ],
            options={
                'verbose_name': '查重文件',
                'verbose_name_plural': '查重文件',
            },
        ),
    ]
